### ISSUE TITLE
Climbatize Config file not found 

### ISSUE THREAD

**Issue by doublehp** [pilkch/climbatize#2]
```
# ./climbatize 
Climbatize
Climbatize Config file "/root/.config/climbatize/climbatize.json" not found
Climbatize Failed to load JSON configuration from "/root/.config/climbatize/climbatize.json", exiting
```

-h did not help :/

Libjson-c does not exist ATM; I used

`# apt install libjson-c2 libjson-c-dev`

`# mkdir -p /root/.config/climbatize`
did not help either

**Comment by pilkch** [comment]
Here is an example one: https://github.com/pilkch/climbatize/blob/master/climbatize.json
In hindsight I should have added -h/--help/-v/--version.  I'll fix it up in the next day or so.
